spring:
  application:
    name: ms-cloudgateway

  cloud:
    gateway:
      routes:
        - id: ms-authorization
          uri: http://localhost:8081
          predicates:
            - Path=/**


  main:
    web-application-type: reactive

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
