spring:
  application:
    name: ms-cloudgateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-authorization
          uri: http://localhost:8081
          predicates:
            - Path=/api/oauth/**, /api/users/**


        - id: ms-products
          uri: http://localhost:8083
          predicates:
            - Path=/categories/**, /api/products/**

  main:
    web-application-type: reactive

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

